sudo: required
language: bash
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export FRONTEND_VERSION=$(cat ./frontend/package.json | grep "\"version\":\ " | head -1 | awk -F'[\"]' '{print $4}')
  - export BACKEND_VERSION=$(cat ./ase/pom.xml | grep "<version>.*</version>" | head -2 | tail -1 | awk -F'[><]' '{print $3}')
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then export POSTFIX="-SNAPSHOT"; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then export POSTFIX=""; fi
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
 provider: script
 skip_cleanup: true
 script: chmod 600 dci.pem && ssh -i "dci.pem" ec2-user@ec2-34-224-17-7.compute-1.amazonaws.com -o ConnectTimeout=300 -o StrictHostKeyChecking=no -t './ASE_CovidDashboard/deploy.sh'
 
 on:
    all_branches: true


addons:
  sonarcloud:
    organization: "ase-project-group"
    token:
      secure: $TOKEN


notifications:
  email: false


