version: "3.9"

services:
    database:
        image: postgres
        environment:
          - POSTGRES_USER=aseuser
          - POSTGRES_PASSWORD=asepassword
          - POSTGRES_DB=covidDatabase
    spring:
        image: manuel57/ase
        build: ase
        ports:
        -   "8080:8080"
        environment:
            - DB_HOST=database
        depends_on:
            - database
        restart: on-failure
    frontend:
        image: manuel57/frontend
        build: frontend
        environment:
            - BACKEND_API_URL=http://host.docker.internal:8080
        ports:
            - '4200:80'
        depends_on:
            -   spring