version: "3.3"

services:
    activemqMessaging:
        container_name: activemqMessaging
        image: rmohr/activemq
        expose:
          - "61616"
          - "61614"
          - "61613"
          - "1883"
          - "8161"
        ports:
          - "8161:8161"
          - "61616:61616"
          - "61614:61614"
          - "61613:61613"
          - "1883:1883"
        restart: always
    database:
        image: postgres
        environment:
          - POSTGRES_USER=aseuser
          - POSTGRES_PASSWORD=asepassword
          - POSTGRES_DB=covidDatabase
    spring:
        image: manuel57/covid-19-dashboard-backend
        build: ase
        ports:
        -   "8080:8080"
        environment:
            - DB_HOST=database
            - ACTIVEMQ_HOST=ec2-34-224-17-7.compute-1.amazonaws.com
        depends_on:
            - database
            - activemqMessaging
        restart: on-failure
    frontend:
        image: manuel57/covid-19-dashboard-frontend
        build: frontend
        environment:
            - BACKEND_API_URL=http://ec2-34-224-17-7.compute-1.amazonaws.com:8080
            - BACKEND_NOTIFICATION_URL=ec2-34-224-17-7.compute-1.amazonaws.com
            - BACKEND_NOTIFICATION_PORT=61614
        ports:
            - '80:80'
        depends_on:
            -   spring